"""
389. Find the Difference

You are given two strings s and t. String t is generated by random
shuffling string s and then adding one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"

Example 2:
Input: s = "", t = "y"
Output: "y"
"""

from collections import Counter


def find_the_difference(s: str, t: str) -> str:
    diff = Counter(t) - Counter(s)
    return next(iter(diff))


if __name__ == "__main__":
    print(find_the_difference("abcd", "abcde"))
    print(find_the_difference("", "y"))
